My personal-layer based Spacemacs configuration.

I focus on customizing Emacs's display in unique ways.

* Description

  See [[./layers/display][display layer for screenshots]].

  See [[./layers/config][config layer for keybindings]].

  - [[./layers/config][config]] :: Typical emacs package configurations.
  - [[./layers/display][display]] :: Houses my ~pretty~ packages and display updates.
       - /pretty-code/ : Program with custom ligatures and symbols, see
         [[http://www.modernemacs.com/post/prettify-mode/][mathematical notation in emacs]].
       - /pretty-eshell/ : Customize eshell information and faces, see
         [[http://www.modernemacs.com/post/custom-eshell/][making eshell your own]].
       - /pretty-fonts/ : All the icons and Fira Code ligature integration.
       - /pretty-magit/ : Commit leaders integration and stylizing, see
         [[http://www.modernemacs.com/post/pretty-magit/][pretty magit - integrating commit leaders]].
       - /pretty-outlines/ : Fancy outline bullets and ellipsis, see [[http://www.modernemacs.com/post/outline-bullets/][fancy outline bullets.]]
  - [[./layers/langs][langs]] :: Language configuration.
  - [[./layers/macros][macros]] :: General purpose macros, base layer for all others.
  - [[./layers/personal][personal]] :: Personal packages that aren't display related.
       - /blog/ : Hugo integration, see [[http://www.modernemacs.com/post/org-mode-blogging/][an Emacs blogging workflow]].
       - /outline-ivy/ : Jump to outlines with ivy, see [[http://www.modernemacs.com/post/outline-ivy/][managing code with outlines]].

  See [[http://www.modernemacs.com/post/migrate-layers/][Migrating to Spacemacs Layers]] to understand this configuration in better depth.

* Install

  ~pretty-fonts~, providing programming ligatures, requires [[https://github.com/tonsky/FiraCode][Fira Code Symbol]]
  ([[https://github.com/tonsky/FiraCode/files/412440/FiraCode-Regular-Symbol.zip][download link]]) font installed. It just uses Fira's ligatures, any font can be
  used in tandem. Failure to install the ligatures or disable pretty-fonts will
  yield strange unicode characters all-over.

  In the ~layers/display/packages.el~, I make heavy use of [[https://github.com/domtronn/all-the-icons.el][all-the-icons]]. If you
  use those packages and keep the icons, make to install it.

  Select the font of your choice ~dotspacemacs-default-font~ in ~init.el~. My
  font, ~operator mono~, is a paid one.

  Theme updates are in ~layers/display/config.el~. Cycle themes with ~SPC T n~.
  I support Zenburn and Solarized-light atm.

  To install clone to your home directory. Set ~ERIC-ONLY?~ at the top of
  ~init.el~ to nil ([[https://github.com/syl20bnr/spacemacs/issues/4979][see spacemacs issue 4979]]).
