My personal-layer based Spacemacs configuration.

I focus on customizing Emacs's display in unique ways.

* Description

  See [[./layers/display][display layer for screenshots]].

  See [[./layers/config][config layer for keybindings]].

  - [[./layers/config][config]] :: Typical Emacs configurations.
  - [[./layers/display][display]] :: Houses my ~pretty~ packages and display-related configuration updates.
    - /pretty-code/ : Program with custom ligatures and symbols, see
      [[http://www.modernemacs.com/post/prettify-mode/][mathematical notation in emacs]].
    - /pretty-eshell/ : Customize eshell information and faces, see
      [[http://www.modernemacs.com/post/custom-eshell/][making eshell your own]].
    - /pretty-fonts/ : All the icons and Fira Code ligature integration.
    - /pretty-magit/ : Commit leaders integration and stylizing, see
      [[http://www.modernemacs.com/post/pretty-magit/][pretty magit - integrating commit leaders]].
    - /pretty-outlines/ : Fancy outline bullets and ellipsis, see [[http://www.modernemacs.com/post/outline-bullets/][fancy outline bullets.]]
  - [[./layers/macros][macros]] :: General purpose macros, base layer for all others.
  - [[./layers/personal][personal]] :: Personal non-display packages.
    - /blog/ : Hugo integration, see [[http://www.modernemacs.com/post/org-mode-blogging/][an Emacs blogging workflow]].
    - /outline-ivy/ : Jump to outlines with ivy, see [[http://www.modernemacs.com/post/outline-ivy/][managing code with outlines]].

  See [[http://www.modernemacs.com/post/migrate-layers/][Migrating to Spacemacs Layers]] to understand this configuration in better depth.

* Install

  Backup and remove your ~.spacemacs~ file and clone to your home directory.

  Icons, fonts, and ligatures require additional steps or you likely will
  experience strange unicode characters all-over.

*** Ligatures

    The ~pretty-fonts~ pkg requires the [[https://github.com/tonsky/FiraCode][Fira Code Symbol]] ([[https://github.com/tonsky/FiraCode/files/412440/FiraCode-Regular-Symbol.zip][download link]]) font
    installed. Any font can be used in-tandem, the link above is an extract of
    just the ligatures.

*** Icons

    In the ~layers/display/packages.el~, I make heavy use of [[https://github.com/domtronn/all-the-icons.el][all-the-icons]].
    The easiest way to install it is running ~M-x all-the-icons-install-fonts~.
    In that file you can customize which icons to include and change.

*** Personalization

    Style your font in ~dotspacemacs-default-font~ in ~init.el~ as normal.

    I've ~Zenburn~ and ~Solarized-light~ themes enabled and configured by
    default. Cycle themes with ~SPC T n~.

    Check out and modify theming changes in ~layers/display/config.el~.
