* Tasks
** TODO Make sure ATT account canceled and refund goes through
** TODO Make sure Public Storage account reset, update cc
   DEADLINE: <2017-02-16 Thu> SCHEDULED: <2017-02-14 Tue>
** TODO Vet appointment for Forest [2017-02-13 Mon] <2005-05-10 Tue 20:30>--<2005-05-10 Tue 22:15>
   DEADLINE: <2017-02-13 Mon>
   :PROPERTIES:
   :Effort:   3
   :END:
** DONE Workout
   CLOSED: [2017-02-13 Mon 21:55]
5 sets Pullups
5 sets Dips
3 sets scaps
4 sets OHP
7:25 mile on treadmill
** DONE Run
   CLOSED: [2017-02-14 Tue 19:26]
3 miles 9:40 avg around dog park
** DONE Workout
   CLOSED: [2017-02-15 Wed 20:15]
5x pullups, 5x dips, 2x scaps, 1x pushups, 45min
** DONE Run
   CLOSED: [2017-02-16 Thu 20:15]
11 min run 9min mile with forest. 35min walk after.
* Agenda tricks
** Timestamps and date completion
1. ', !' for inactive timestamps (don't affect agenda views, show up in name)
2. +1w repeat weekly, +2tue, -wed last Wednesday
3. ++1w for 1 week after last completion
4. time completion: 11am(- or -- or +)2:15
5. In timestamp completion - 'Fri', 'sep 15'
6. S-right/S-left for forward/backward day in prompt
7. http://orgmode.org/manual/The-date_002ftime-prompt.html#The-date_002ftime-prompt

** Checkboxes
http://orgmode.org/manual/Checkboxes.html#Checkboxes

** Habits
http://orgmode.org/manual/Tracking-your-habits.html#Tracking-your-habits

** g evil commands
'g y' copies and comments, command I've been looking for
'g x' takes a motion and highlights. Second 'g x' transposes the two selections
'g X' cancels a single select
'g v' restores last visual selection (great for paste and tab)
'g q' fills from motion. Fill wraps the text to 80chars
'g i' resumes last insert (very good to master this one)
'g ;' goto last change
