#+TITLE: Macros Layer

* Description

Macros layer serves as a base layer that all other personal packages declare
dependence on in their respective ~layers.el~.

I try to be reasonable with defining a minimal amount of macros to make
copy-pasting components of my config easier.

It allows:

1. Certain universal packages (dash, dash-functional, s) to be guaranteed by a
   single ~(require macros)~ in the package and ~(:after macros)~ in the owning
   layer.
2. Universally useful functions to also be made available.

This enables the seemingly-but-not-actually simple idea of a core set of
packages beyond what is defined in ~spacemacs-bootstrap~.

Note that in-fact ~dash~ actually is available always as its loaded in
~.emacs.d/core/core-documentation~.

** Macros and Functions

- ~define-keys~ :: Takes many bindings.
- ~evil-global-set-keys~ :: Takes many states and bindings.
- ~with-face~ :: Shorthand for ~propertize s 'face '(props)~
- ~with-dir~ :: Executes forms within a directory.

** Packages

- ~dash~
- ~dash-functional~
- ~s~
